### ISSUE TITLE
Cosmetics

### ISSUE THREAD

**Issue by JellinaP** [JellinaP/faceMAP#8]
-	Progress bar during processing
-	Change ‘ROI’ field to AOI (standard in the eye tracking field)
-	Export resulting csv.file with correct extension (fixations_facemap.csv)

**Comment by JelleVE** [comment]
AOI fields:
- AOI_voronoi
- AOI_upper_lower

output_file:
mapping_{pid}.csv

**Comment by JelleVE** [comment]
Can be closed. Progress bar remains (#4).
